export const GET_HIGHTLIGHTS = 'GET_HIGHTLIGHTS';
export const GET_BREAKFAST = 'GET_BREAKFAST';
export const GET_MEAL = 'GET_MEAL';
export const GET_DINNER = 'GET_DINNER';
export const GET_PORMOTIONS = 'GET_PORMOTIONS';
export const GET_DRINKS = 'GET_DRINKS';

export const POST_DISHES_TO_STATE = 'POST_DISHES_TO_STATE';
